version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=flask
            - POSTGRES_DB=bot
        ports:
            - "5432:5432"

    gunicorn:
        build: .
        volumes:
            - .:/code
        environment:
            - FLASK_APP=bot
        command: >
            bash -c "flask db migrate &&
            flask db upgrade &&
            gunicorn --preload --log-level 'info' -b gunicorn:5000 'bot:create_app()'"
        depends_on:
            - db

    ngrok:
        image: wernight/ngrok:latest
        ports:
            - 4040:4040
        environment:
            NGROK_PROTOCOL: HTTP
            NGROK_PORT: gunicorn:5000
            NGROK_DEBUG: "true"
        depends_on:
            - gunicorn