version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=flask
            - POSTGRES_DB=bot
        ports:
            - "5432:5432"