"""empty message

Revision ID: 016e04c7ede3
Revises: 
Create Date: 2021-04-28 19:59:20.978966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016e04c7ede3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    op.add_column('group', sa.Column('group_name', sa.String(), nullable=True))
    op.add_column('group', sa.Column('p_id', sa.Integer(), nullable=False))
    op.drop_column('group', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('group', 'p_id')
    op.drop_column('group', 'group_name')
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='groups_pkey')
    )
    # ### end Alembic commands ###
