"""empty message

Revision ID: 89ab2255b615
Revises: 016e04c7ede3
Create Date: 2021-04-28 20:05:10.014399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ab2255b615'
down_revision = '016e04c7ede3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancelation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_the_week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancelation')
    # ### end Alembic commands ###
