"""empty message

Revision ID: ad77df288bf7
Revises: 89ab2255b615
Create Date: 2021-04-28 20:32:24.255672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad77df288bf7'
down_revision = '89ab2255b615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancelation', sa.Column('day_of_the_week_dummy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cancelation', 'day_of_the_week_dummy')
    # ### end Alembic commands ###
