"""empty message

Revision ID: f5eb0133eed7
Revises: 1482651823b9
Create Date: 2021-04-28 21:24:14.695115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5eb0133eed7'
down_revision = '1482651823b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_the_week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cancelation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancelation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day_of_the_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cancelation_pkey')
    )
    op.drop_table('cancellation')
    # ### end Alembic commands ###
